#include "stm32f10x.h"          										        // Device header

void gpioInit(){
	RCC->APB2ENR |= RCC_APB2ENR_IOPCEN | RCC_APB2ENR_IOPAEN;											  // cnf mode 10 00

	GPIOC->CRH &= ~(GPIO_CRH_CNF9 | GPIO_CRH_MODE9);
	GPIOC->CRH |= GPIO_CRH_MODE9_1;	
	
	GPIOC->CRH &= ~(GPIO_CRH_CNF8 | GPIO_CRH_MODE8);
	GPIOC->CRH |= GPIO_CRH_MODE8_1;	
	
	GPIOC->CRL &= ~(GPIO_CRL_CNF0 | GPIO_CRL_MODE0);
	GPIOC->CRL |= GPIO_CRL_MODE0_1;													 //2mhz output configure
	
	GPIOC->CRL &= ~(GPIO_CRL_CNF1 | GPIO_CRL_MODE1);
	GPIOC->CRL |= GPIO_CRL_MODE1_1;	
	
	GPIOC->CRL &= ~(GPIO_CRL_CNF2 | GPIO_CRL_MODE2);
	GPIOC->CRL |= GPIO_CRL_MODE2_1;	
	
	GPIOC->CRL &= ~(GPIO_CRL_CNF3 | GPIO_CRL_MODE3);
	GPIOC->CRL |= GPIO_CRL_MODE3_1;	
	
	GPIOC->CRL &= ~(GPIO_CRL_CNF4 | GPIO_CRL_MODE4);
	GPIOC->CRL |= GPIO_CRL_MODE4_1;	
	
	GPIOC->CRL &= ~(GPIO_CRL_CNF5 | GPIO_CRL_MODE5);
	GPIOC->CRL |= GPIO_CRL_MODE5_1;	
	
	GPIOC->CRL &= ~(GPIO_CRL_CNF6 | GPIO_CRL_MODE6);
	GPIOC->CRL |= GPIO_CRL_MODE6_1;	
	
	GPIOC->CRL &= ~(GPIO_CRL_CNF7 | GPIO_CRL_MODE7);
	GPIOC->CRL |= GPIO_CRL_MODE7_1;	
	
//	GPIOC->ODR |=	table[4];
}
void InitEncoder(){
  RCC->APB2ENR |= RCC_APB2ENR_IOPAEN;
	RCC->APB1ENR |= RCC_APB1ENR_TIM3EN;
	
	GPIOA->CRL &=~ (GPIO_CRL_CNF6 | GPIO_CRL_MODE6);
	GPIOA->CRL |= GPIO_CRL_CNF6_1;									//ODR = 0;
	
	GPIOA->CRL &=~ (GPIO_CRL_CNF7 | GPIO_CRL_MODE7);
	GPIOA->CRL |= GPIO_CRL_CNF7_1;									//ODR = 0;
	
	TIM3->CCMR1 |= TIM_CCMR1_IC1F | TIM_CCMR1_IC2F; //INPUT COMPARE FILTER N = 8 Fsampling = 24Mhz
	TIM3->CCMR1 |= TIM_CCMR1_CC1S_0 | TIM_CCMR1_CC2S_0; //CAPTURE COMP SELECTION SETTING HOW   TI1 & TI2   INPUT COMPARE & MAPPED HOW TI1 & 2
	
	TIM3->CCER &= ~(TIM_CCER_CC1P | TIM_CCER_CC2P); //CONF POLAR HOW RISING FRONT DEFAULT 0
	
	TIM3->SMCR |= TIM_SMCR_SMS_0 | TIM_SMCR_SMS_1;  // SLAVE MODE CONTROL REGISTER - SL MOD SELEC 011 COUNT ALL CHANNEL 
	
	TIM3->ARR   = 256;                              //AUTO-RELOAD REG
	TIM3->CR1 |= TIM_CR1_CEN;												// COUNT ENABLE
		
	TIM3->CNT = 0;
}

